name: percepticon
favicon: null
layout_spectrum: 0.1723139276728034
typography_spectrum: 0.8777701538056135
title: is it the future yet?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181a15'
    - '#49737e'
    - '#009af1'
    - '#dcd8c2'
    - '#d23f00'
  brandStrength: 0.0933858617208898
  lightness: 0.951216810150072
  saturation: 0.204833609983325
  rhythmicContrast: 0.14331751549616456
purpose: []
